package mappings;
// Generated Nov 28, 2015 1:33:19 PM by Hibernate Tools 3.6.0



/**
 * Distribution generated by hbm2java
 */
public class Distribution  implements java.io.Serializable {


     private Integer iddistribution;
     private Sales sales;
     private String destination;
     private String date;
     private String charge;

    public Distribution() {
    }

	
    public Distribution(Sales sales) {
        this.sales = sales;
    }
    public Distribution(Sales sales, String destination, String date, String charge) {
       this.sales = sales;
       this.destination = destination;
       this.date = date;
       this.charge = charge;
    }
   
    public Integer getIddistribution() {
        return this.iddistribution;
    }
    
    public void setIddistribution(Integer iddistribution) {
        this.iddistribution = iddistribution;
    }
    public Sales getSales() {
        return this.sales;
    }
    
    public void setSales(Sales sales) {
        this.sales = sales;
    }
    public String getDestination() {
        return this.destination;
    }
    
    public void setDestination(String destination) {
        this.destination = destination;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getCharge() {
        return this.charge;
    }
    
    public void setCharge(String charge) {
        this.charge = charge;
    }




}


