package mappings;
// Generated Nov 28, 2015 1:33:19 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private Integer idorders;
     private Product product;
     private User user;
     private String date;
     private String amount;
     private String discount;
     private String quantity;
     private Set saleses = new HashSet(0);

    public Orders() {
    }

	
    public Orders(Product product, User user) {
        this.product = product;
        this.user = user;
    }
    public Orders(Product product, User user, String date, String amount, String discount, String quantity, Set saleses) {
       this.product = product;
       this.user = user;
       this.date = date;
       this.amount = amount;
       this.discount = discount;
       this.quantity = quantity;
       this.saleses = saleses;
    }
   
    public Integer getIdorders() {
        return this.idorders;
    }
    
    public void setIdorders(Integer idorders) {
        this.idorders = idorders;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }
    public String getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(String discount) {
        this.discount = discount;
    }
    public String getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }
    public Set getSaleses() {
        return this.saleses;
    }
    
    public void setSaleses(Set saleses) {
        this.saleses = saleses;
    }




}


