package mappings;
// Generated Nov 28, 2015 1:33:19 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer idproduct;
     private String catogeroy;
     private String name;
     private String price;
     private String cc;
     private String mountType;
     private Set orderses = new HashSet(0);

    public Product() {
    }

    public Product(String catogeroy, String name, String price, String cc, String mountType, Set orderses) {
       this.catogeroy = catogeroy;
       this.name = name;
       this.price = price;
       this.cc = cc;
       this.mountType = mountType;
       this.orderses = orderses;
    }
   
    public Integer getIdproduct() {
        return this.idproduct;
    }
    
    public void setIdproduct(Integer idproduct) {
        this.idproduct = idproduct;
    }
    public String getCatogeroy() {
        return this.catogeroy;
    }
    
    public void setCatogeroy(String catogeroy) {
        this.catogeroy = catogeroy;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }
    public String getCc() {
        return this.cc;
    }
    
    public void setCc(String cc) {
        this.cc = cc;
    }
    public String getMountType() {
        return this.mountType;
    }
    
    public void setMountType(String mountType) {
        this.mountType = mountType;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }




}


