package mappings;
// Generated Nov 28, 2015 1:33:19 PM by Hibernate Tools 3.6.0



/**
 * SalesReturn generated by hbm2java
 */
public class SalesReturn  implements java.io.Serializable {


     private Integer idsalesReturn;
     private Sales sales;
     private String date;
     private String note;

    public SalesReturn() {
    }

	
    public SalesReturn(Sales sales) {
        this.sales = sales;
    }
    public SalesReturn(Sales sales, String date, String note) {
       this.sales = sales;
       this.date = date;
       this.note = note;
    }
   
    public Integer getIdsalesReturn() {
        return this.idsalesReturn;
    }
    
    public void setIdsalesReturn(Integer idsalesReturn) {
        this.idsalesReturn = idsalesReturn;
    }
    public Sales getSales() {
        return this.sales;
    }
    
    public void setSales(Sales sales) {
        this.sales = sales;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


