package mappings;
// Generated Nov 28, 2015 1:33:19 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Sales generated by hbm2java
 */
public class Sales  implements java.io.Serializable {


     private Integer idsales;
     private Orders orders;
     private User user;
     private String cusName;
     private String productId;
     private String engCategory;
     private String model;
     private String cc;
     private String MType;
     private String contactNo;
     private String quantity;
     private String discount;
     private String price;
     private String date;
     private Set salesReturns = new HashSet(0);
     private Set distributions = new HashSet(0);

    public Sales() {
    }

    public Sales(Orders orders, User user, String cusName, String productId, String engCategory, String model, String cc, String MType, String contactNo, String quantity, String discount, String price, String date, Set salesReturns, Set distributions) {
       this.orders = orders;
       this.user = user;
       this.cusName = cusName;
       this.productId = productId;
       this.engCategory = engCategory;
       this.model = model;
       this.cc = cc;
       this.MType = MType;
       this.contactNo = contactNo;
       this.quantity = quantity;
       this.discount = discount;
       this.price = price;
       this.date = date;
       this.salesReturns = salesReturns;
       this.distributions = distributions;
    }
   
    public Integer getIdsales() {
        return this.idsales;
    }
    
    public void setIdsales(Integer idsales) {
        this.idsales = idsales;
    }
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getCusName() {
        return this.cusName;
    }
    
    public void setCusName(String cusName) {
        this.cusName = cusName;
    }
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }
    public String getEngCategory() {
        return this.engCategory;
    }
    
    public void setEngCategory(String engCategory) {
        this.engCategory = engCategory;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public String getCc() {
        return this.cc;
    }
    
    public void setCc(String cc) {
        this.cc = cc;
    }
    public String getMType() {
        return this.MType;
    }
    
    public void setMType(String MType) {
        this.MType = MType;
    }
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }
    public String getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }
    public String getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(String discount) {
        this.discount = discount;
    }
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public Set getSalesReturns() {
        return this.salesReturns;
    }
    
    public void setSalesReturns(Set salesReturns) {
        this.salesReturns = salesReturns;
    }
    public Set getDistributions() {
        return this.distributions;
    }
    
    public void setDistributions(Set distributions) {
        this.distributions = distributions;
    }




}


