package mappings;
// Generated Nov 28, 2015 1:33:19 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * UserLogin generated by hbm2java
 */
public class UserLogin  implements java.io.Serializable {


     private Integer idtable1;
     private String username;
     private String password;
     private Set users = new HashSet(0);

    public UserLogin() {
    }

    public UserLogin(String username, String password, Set users) {
       this.username = username;
       this.password = password;
       this.users = users;
    }
   
    public Integer getIdtable1() {
        return this.idtable1;
    }
    
    public void setIdtable1(Integer idtable1) {
        this.idtable1 = idtable1;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


