package mappings;
// Generated Nov 28, 2015 1:33:19 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer iduser;
     private UserLogin userLogin;
     private UserTypes userTypes;
     private String fname;
     private String lname;
     private String address;
     private String email;
     private String telNo;
     private String postalCode;
     private String country;
     private Set orderses = new HashSet(0);
     private Set saleses = new HashSet(0);

    public User() {
    }

	
    public User(UserLogin userLogin, UserTypes userTypes) {
        this.userLogin = userLogin;
        this.userTypes = userTypes;
    }
    public User(UserLogin userLogin, UserTypes userTypes, String fname, String lname, String address, String email, String telNo, String postalCode, String country, Set orderses, Set saleses) {
       this.userLogin = userLogin;
       this.userTypes = userTypes;
       this.fname = fname;
       this.lname = lname;
       this.address = address;
       this.email = email;
       this.telNo = telNo;
       this.postalCode = postalCode;
       this.country = country;
       this.orderses = orderses;
       this.saleses = saleses;
    }
   
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
    public UserLogin getUserLogin() {
        return this.userLogin;
    }
    
    public void setUserLogin(UserLogin userLogin) {
        this.userLogin = userLogin;
    }
    public UserTypes getUserTypes() {
        return this.userTypes;
    }
    
    public void setUserTypes(UserTypes userTypes) {
        this.userTypes = userTypes;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelNo() {
        return this.telNo;
    }
    
    public void setTelNo(String telNo) {
        this.telNo = telNo;
    }
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }
    public Set getSaleses() {
        return this.saleses;
    }
    
    public void setSaleses(Set saleses) {
        this.saleses = saleses;
    }




}


